### ISSUE TITLE
[BUG] touch not recognized

### ISSUE THREAD

**Issue by dmartins-095** [usmanmehmood55/c-toolkit#30]
**Describe the bug**
Error when running a project about 'touch' not recognized.

**To Reproduce**
1. click the status bar button Debug and choose Debug
2. Click the status bar button Run
After compilation, the error message about not recognized 'touch' appears in the Terminal

**Expected behavior**
Running the project without errors and being able to debug it with breakpoints

**Screenshots**

PS C:\Work\Work24a\Benchs\myvscodeProj\ProjDM01> cmake -G Ninja -B build -D CMAKE_BUILD_TYPE=Debug ; ninja -C build ; touch c:\Work\Work24a\Benchs\myvscodeProj\ProjDM01\build\z_build_complete
-- The C compiler identification is GNU 8.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done (4.8s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Work/Work24a/Benchs/myvscodeProj/ProjDM01/build
ninja: Entering directory `build'
[2/2] Linking C executable ProjDM01.exe
   text    data     bss     dec     hex filename
   9724    2228    2432   14384    3830 C:/Work/Work24a/Benchs/myvscodeProj/ProjDM01/build/ProjDM01.exe
touch : The term 'touch' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path 
is correct and try again.
At line:1 char:70
+ ... a -B build -D CMAKE_BUILD_TYPE=Debug ; ninja -C build ; touch c:\Work ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (touch:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Please complete the following information:**
- OS: [Windows]
- Architecture: [Intel x64]
- Versions of tools installed
  - GCC  : (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
  - GDB : GNU gdb (GDB) 8.1
  - CMake : version 3.30.0
  - Ninja : 1.12.1

**Additional context**

**Comment by usmanmehmood55** [comment]
It looks like `busybox` is missing from your system. Normally the extension should have detected that and offered to install it. 

You can use the command `C Toolkit: Search For Build Tools` to trigger the search manually. 

It would also be helpful if you can show the text from the "output" tab for the extension.

**Comment by usmanmehmood55** [comment]
Closing for now, due to inactivity.
